[package]
name = "conway_benchmark"
publish = false
edition.workspace = true
rust-version.workspace = true

[dependencies]
burn = { workspace = true, features = ["fusion"] }
bunsen = { path = "../../crates/public/bunsen" }

clap = { workspace = true, features = ["derive"] }
indicatif = { workspace = true }

[lints]
workspace = true

[features]
default = ["flex"]
cuda = ["burn/cuda"]
metal = ["burn/metal"]
wgpu = ["burn/wgpu"]
flex = ["burn/flex"]
