[package]
name = "bunsen-arrow-dataloaders"
authors.workspace = true
version.workspace = true
rust-version.workspace = true
edition.workspace = true

repository.workspace = true
license.workspace = true
description = "bunsen preview: Arrow-backed chat dataloader with tokenization for training"


[lints]
workspace = true


[dependencies]
wordchipper = { workspace = true, features = ["client"] }

burn = { workspace = true, features = ["train"] }
rand = { workspace = true }
parquet = { workspace = true, features = ["arrow"] }
arrow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
log = { workspace = true }


[dev-dependencies]
wordchipper = { workspace = true, features = ["testing"] }
