//! # Silero VAD validation.
//!
//! Validates [`bunsen`]'s Silero VAD against the implementation it was
//! transliterated from: a Rust model generated by `burn_onnx::ModelGen` from
//! the upstream `silero_vad` ONNX graph. Both run inside `burn`, so a
//! disagreement is a bunsen bug rather than a framework difference.
//!
//! ```sh
//! cargo test --release -p silero-model-validation --features wgpu
//! ```
//!
//! ## Why the reference is not in `bunsen`
//!
//! It used to be, as `kits::speech::silero_vad::reference`. A generated
//! transliteration of a graph is validation machinery — it exists to be
//! disagreed with — and shipping it in the library put a second, redundant
//! Silero implementation on the public surface.
//!
//! The *weights* are a different matter and stayed put:
//! `bunsen_bundled_silero::silero::BURNPACK_WEIGHTS` is what
//! `SileroVadCollection::load_pretrained` loads, so `bunsen` still depends on
//! that crate. Only the reference *model* moved here.
//!
//! ## A backend, not a checkpoint
//!
//! Unlike Whisper, nothing here is fetched: the graph is committed in
//! `bunsen-bundled-silero` and the weights ship with it. So a backend feature
//! is all this crate takes, and it is worth passing: `PerformanceBackend`
//! falls through to `Flex` when none reaches `bunsen`, and the cross-checks
//! are compiled either way. A run without one does not fail — it quietly
//! measures the CPU and passes, which is not worth the wall clock.
//!
//! Nothing here enforces that. These cross-checks predate the `gpu-tests`
//! convention (see `STYLE.md`) and are not yet gated by it.

/// The reference model, generated from the upstream ONNX graph.
pub mod reference {
    pub use bunsen_bundled_silero::onnx_gen::*;

    /// Reference ONNX Model.
    pub type ReferenceModel<B> = Model<B>;
}

mod cross_test;
