//! # Silero VAD validation.
//!
//! Validates [`bunsen`]'s Silero VAD against the implementation it was
//! transliterated from: a Rust model generated by `burn_onnx::ModelGen` from
//! the upstream `silero_vad` ONNX graph. Both run inside `burn`, so a
//! disagreement is a bunsen bug rather than a framework difference.
//!
//! ```sh
//! cargo test --release -p silero-model-validation --features wgpu
//! ```
//!
//! ## Why the reference is not in `bunsen`
//!
//! It used to be, as `kits::speech::silero_vad::reference`. A generated
//! transliteration of a graph is validation machinery — it exists to be
//! disagreed with — and shipping it in the library put a second, redundant
//! Silero implementation on the public surface.
//!
//! The *weights* are a different matter and stayed put:
//! `bunsen_bundled_silero::silero::BURNPACK_WEIGHTS` is what
//! `SileroVadCollection::load_pretrained` loads, so `bunsen` still depends on
//! that crate. Only the reference *model* moved here.
//!
//! ## A backend, not a checkpoint
//!
//! Unlike Whisper, nothing here is fetched: the graph is committed in
//! `bunsen-bundled-silero` and the weights ship with it. A backend
//! feature is still required, because `PerformanceBackend` falls back to CPU
//! silently when none is selected and a validation run that quietly uses the
//! CPU backend is not worth the wall clock. Without one the cross-checks are
//! not compiled, and a single ignored test says so.

/// The reference model, generated from the upstream ONNX graph.
pub mod reference {
    pub use bunsen_bundled_silero::onnx_gen::*;

    /// Reference ONNX Model.
    pub type ReferenceModel<B> = Model<B>;
}

mod cross_test;
