[package]
name = "resnet_tiny"
publish = false
rust-version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []
wgpu = ["burn/wgpu"]
cuda = ["burn/cuda"]
metal = ["burn/metal"]


[dependencies]
burn = { workspace = true, features = ["train", "fusion", "autotune", "vision", "dataset", "flex"] }
bunsen = { path = "../../crates/public/bunsen" }
bunsen-firehose = { path = "../../crates/public/bunsen-firehose" }
bunsen-firehose-image = { path = "../../crates/public/bunsen-firehose-image" }

serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive"] }

rand = { workspace = true }
anyhow = { workspace = true }

