[workspace]
# Require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "crates/*",
]

[workspace.package]
edition = "2024"
rust-version = "1.94.1"
version = "0.0.3"
repository = "https://github.com/zspacelabs/bunsen"
license = "MIT or Apache-2.0"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
double_must_use = "allow"
doc_markdown = "warn"


[workspace.dependencies]
burn = "0.20.1"
burn-import = "0.20.1"
dirs = "6.0.0"

bimm-contracts = "0.19.2"

# Burn coupled-dependencies
# globwalk = "0.9.1"
serde = "1.0.228"
serde_json = "1.0.145"

clap = "4.5.51"

crc = "3.4.0"

anyhow = "1.0.100"

# Test and/or Examples dependencies
criterion = "0.7.0"
hamcrest = "0.1.5"
indoc = "2.0.7"
num-traits = "0.2.19"

