[workspace]
# Require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "crates/*",
]

[workspace.package]
edition = "2024"
rust-version = "1.94.1"
version = "0.0.4"
repository = "https://github.com/zspacelabs/bunsen"
license = "MIT or Apache-2.0"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
double_must_use = "allow"
doc_markdown = "warn"


[workspace.dependencies]
burn = "0.20.1"
burn-import = "0.20.1"
dirs = "6.0.0"

# Burn coupled-dependencies
# globwalk = "0.9.1"
serde = "1.0.228"
serde_json = "1.0.145"

clap = "4.5.51"

crc = "3.4.0"

anyhow = "1.0.100"

# Test and/or Examples dependencies
hamcrest = "0.1.5"
indoc = "2.0.7"
num-traits = "0.2.19"

# macro dependencies
proc-macro2 = { version = "^1.0.97" }
syn = { version = "2.0.111" }
quote = { version = "^1.0.45" }

# Test and/or Examples dependencies
criterion = { version = "0.8.2" }

hashbrown = { version = "0.17.0" }
paste = "1.0.9"
spanned_error_message = "0.1.0"
thiserror = "2.0.18"
strum = "0.28.0"
xot = "0.31.2"
xee-xpath = "0.1.5"
