[package]
name = "bunsen"
readme = "../../README.md"
edition.workspace = true

authors.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true

rust-version.workspace = true
homepage = "https://zspacelabs.ai/bunsen/book"
documentation = "https://docs.rs/bunsen/latest/"
description = "bunsen is a batteries included common library for burn"

[lints]
workspace = true


[[bench]]
name = "drop_block"
harness = false

[[bench]]
name = "contracts"
harness = false

[[bench]]
name = "math"
harness = false

[[bench]]
name = "lbm"
harness = false


[features]
default = [
    "reflection",
    "train",
    "testing",
    "store",
]

std = [
    "burn/std",
]

## Enable the XmlModuleTree reflection api for querying and transforming modules.
reflection = [
    "std",
    "dep:xot",
    "dep:paste",
    "dep:xee-xpath",
    "dep:spanned_error_message",
]

## Enable the burn-store.
store = [
    "std",
    "cache",
    "burn/store",
    "burn-store/pytorch"
]

## Enable features to use with `burn/train`.
train = [
    "std",
    "burn/train",
    "dep:hashbrown",
]

## Enable the disk cache.
cache = [
    "std",
    "downloader/default-tls",
]

## Enables testing support features.
testing = [
    "flex"
]

## Enable the cuda backend in the bunsen build.
## This will impact the bunsen::support::testing::PerformanceBackend choice.
## Dependents which enable backends for burn without enabling them for bunsen
## can still use those backends with bunsen; only bunse specific features will
## be disabled.
cuda = ["burn/cuda"]
## Enable the cuda backend in the bunsen build.
## This will impact the bunsen::support::testing::PerformanceBackend choice.
## Dependents which enable backends for burn without enabling them for bunsen
## can still use those backends with bunsen; only bunse specific features will
## be disabled.
metal = ["burn/metal"]
## Enable the cuda backend in the bunsen build.
## This will impact the bunsen::support::testing::PerformanceBackend choice.
## Dependents which enable backends for burn without enabling them for bunsen
## can still use those backends with bunsen; only bunse specific features will
## be disabled.
wgpu = ["burn/wgpu"]
## Enable the cuda backend in the bunsen build.
## This will impact the bunsen::support::testing::PerformanceBackend choice.
## Dependents which enable backends for burn without enabling them for bunsen
## can still use those backends with bunsen; only bunse specific features will
## be disabled.
flex = ["burn/flex"]


[dependencies]
bunsen-contracts-macros = { version = "0.22.0", path = "../bunsen-contracts-macros" }

burn = { workspace = true }
burn-store = { workspace = true, optional = true }

# burner-locked public deps:
hashbrown = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
crc = { workspace = true }

directories-next = { workspace = true }
# features=["tui"] incompatible with conflicting indicatif versions.
downloader = { workspace = true, default-features = false }

num-traits = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

document-features = { workspace = true }
paste = { workspace = true, optional = true }

spanned_error_message = { workspace = true, optional = true }
xot = { workspace = true, optional = true }
xee-xpath = { workspace = true, optional = true }


[dev-dependencies]
bunsen = { path = ".", features = ["testing"] }
burn = { workspace = true, features = ["autodiff"] }

serial_test = { workspace = true }
nearly = { workspace = true }
hamcrest = { workspace = true }
indoc = { workspace = true }
criterion = { workspace = true }

