[package]
name = "bunsen"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/bunsen/latest/"
description = "bunsen is a community companion library for burn"

[lints]
workspace = true

[features]
default = [
    "reflection",
    "train",
    "cache",
]
std = [
    "bunsen-contracts/std",
]

reflection = [
    "std",
    "dep:xot",
    "dep:paste",
    "dep:xee-xpath",
    "dep:spanned_error_message",
]
train = [
    "std",
    "burn/train",
    "dep:hashbrown",
]
cache = [
    "std",
    "dep:dirs",
    "dep:crc",
    "burn/network"
]

wgpu = ["burn/wgpu"]
cuda = ["burn/cuda"]

[dependencies]
bunsen-contracts = { path = "../bunsen-contracts", version = "0.21.0" }

# VERIFY: There was a dep/gate bug that requires "ndarray" when using "network".
burn = { workspace = true, features = ["network"] }
# burn-locked public deps:
hashbrown = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

dirs = { workspace = true, optional = true }
crc = { workspace = true, optional = true }

anyhow = { workspace = true }
num-traits = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

spanned_error_message = { workspace = true, optional = true }
paste = { workspace = true, optional = true }
xot = { workspace = true, optional = true }
xee-xpath = { workspace = true, optional = true }

[dev-dependencies]
burn = { workspace = true, features = ["autodiff", "wgpu"] }
hamcrest = { workspace = true }
indoc = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "drop_block"
harness = false
