[package]
name = "bunsen"
readme = "../../README.md"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/bunsen/latest/"
description = "bunsen is acceleration tooling for burn"

[lints]
workspace = true


[[bench]]
name = "drop_block"
harness = false

[[bench]]
name = "contracts"
harness = false

[[bench]]
name = "math"
harness = false


[features]
default = [
    "reflection",
    "train",
    "testing",
]
std = [
    "burn/std",
]

## Enable the XmlModuleTree reflection api for querying and transforming modules.
reflection = [
    "std",
    "dep:xot",
    "dep:paste",
    "dep:xee-xpath",
    "dep:spanned_error_message",
]

## Enable features to use with `burn/train`.
train = [
    "std",
    "burn/train",
    "dep:hashbrown",
]

## Enable the disk cache.
cache = [
    "std",
    "dep:bunsen-cache",
]

## Enables testing support features.
testing = [
    "flex"
]

## Enable the cuda backend in the bunsen build.
## This will impact the bunsen::support::testing::PerfTestBackend choice.
## Dependents which enable backends for burn without enabling them for bunsen
## can still use those backends with bunsen; only bunse specific features will
## be disabled.
cuda = ["burn/cuda"]
## Enable the cuda backend in the bunsen build.
## This will impact the bunsen::support::testing::PerfTestBackend choice.
## Dependents which enable backends for burn without enabling them for bunsen
## can still use those backends with bunsen; only bunse specific features will
## be disabled.
metal = ["burn/metal"]
## Enable the cuda backend in the bunsen build.
## This will impact the bunsen::support::testing::PerfTestBackend choice.
## Dependents which enable backends for burn without enabling them for bunsen
## can still use those backends with bunsen; only bunse specific features will
## be disabled.
wgpu = ["burn/wgpu"]
## Enable the cuda backend in the bunsen build.
## This will impact the bunsen::support::testing::PerfTestBackend choice.
## Dependents which enable backends for burn without enabling them for bunsen
## can still use those backends with bunsen; only bunse specific features will
## be disabled.
flex = ["burn/flex"]


[dependencies]
bunsen-cache = { path = "../bunsen-cache", version = "0.21.0", optional = true }
# bunsen-contracts = { path = "../bunsen-contracts", version = "0.21.0-pre.6", features = ["burn"] }
bunsen-contracts-macros = { version = "0.21.0", path = "../bunsen-contracts-macros" }

burn = { workspace = true }
# burner-locked public deps:
hashbrown = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

document-features = { workspace = true }

anyhow = { workspace = true }
num-traits = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

spanned_error_message = { workspace = true, optional = true }
paste = { workspace = true, optional = true }
xot = { workspace = true, optional = true }
xee-xpath = { workspace = true, optional = true }


[dev-dependencies]
bunsen = { path = ".", features = ["testing"] }
burn = { workspace = true, features = ["autodiff"] }
hamcrest = { workspace = true }
indoc = { workspace = true }
criterion = { workspace = true }

