[package]
name = "lbm2d_vis"
publish = false
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true


[features]
default = ["flex"]
cuda = ["burn/cuda"]
metal = ["burn/metal"]
wgpu = ["burn/wgpu"]
flex = ["burn/flex"]


[dependencies]
burn = { workspace = true, features = ["fusion", "autotune"] }
bunsen = { path = "../../crates/public/bunsen" }

clap = { workspace = true, features = ["derive"] }
indicatif = { workspace = true }

piston = { workspace = true }
piston2d-graphics = { workspace = true }
pistoncore-glutin_window = { workspace = true }
piston2d-opengl_graphics = { workspace = true }
gl = { workspace = true }
rand = { workspace = true }
