[package]
name = "dl-test"
rust-version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
bunsen-arrow-dataloaders = { path = "../.." }
zsl-data-cache = { path = "../../../../../examples/zsl-data-cache" }
wordchipper = { workspace = true, features = ["client"] }
wordchipper-cli-util = { workspace = true }

rand = { workspace = true }
burn = { workspace = true, features = ["cuda"] }
log = { workspace = true }
clap = { workspace = true, features = ["derive"] }

humansize = { workspace = true }