[package]
name = "bunsen-firehose"
rust-version.workspace = true
edition.workspace = true

authors.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
documentation = "https://docs.rs/bunsen-firehose/latest/"
description = "bunsen dataloader / processing pipeline"

[lints]
workspace = true

[dependencies]
burn = { workspace = true, features = ["std", "dataset", "vision"] }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

num-traits = { workspace = true }

globwalk = { workspace = true }

anyhow = { workspace = true }

inventory = { workspace = true }

indoc = { workspace = true }

regex = { workspace = true }
regex-macro = { workspace = true }

