[package]
name = "whisper-dev"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true


[lints]
workspace = true

[features]
default = ["flex"]
cuda = ["burn/cuda", "bunsen/cuda"]
metal = ["burn/metal", "bunsen/metal"]
wgpu = ["burn/wgpu", "bunsen/wgpu"]
flex = ["burn/flex", "bunsen/flex"]


[dependencies]
burn = { workspace = true, features = ["store", "fusion"] }
burn-store = { workspace = true, features = ["pytorch"] }

bunsen = { path = "../../crates/public/bunsen" }

clap = { workspace = true, features = ["derive"] }
