//! # The anti-alias filter, in two tensor formulations.
//!
//! The reference decimates 16 kHz to 4 kHz, and guards the new Nyquist with a
//! five-section Direct-Form-II IIR cascade. This is the one part of the pitch
//! estimator with two genuinely different tensor formulations, so it is where
//! the reference and optimized tiers diverge — every other stage has a single
//! natural translation.
//!
//! ```text
//! [batch, steps·hop]  ->  [batch, steps·hop/4]
//! ```
//!
//! ## [`PitchAntiAliasConfig::Recurrence`] — the reference tier
//!
//! The cascade transcribed literally: five sections, each stepping sample by
//! sample through `w0 = x − a₁w₁ − a₂w₂`. Batched across streams but **not**
//! across samples — the recurrence forbids it — so it costs `5 × samples`
//! sequential steps. At 256 samples per hop that is 1280 steps per hop, which
//! is fine for a short equivalence check and hopeless for a real workload.
//!
//! It exists to answer one question the optimized tier cannot: *was the
//! algorithm translated correctly?* Comparing only against the host would
//! conflate a translation error with the deliberate approximation below.
//!
//! ## [`PitchAntiAliasConfig::TruncatedFir`] — the default
//!
//! The same LTI system realized as a truncated impulse response, with the ×4
//! decimation folded into the kernel, evaluated as one GEMM:
//!
//! ```text
//! y[m] = Σ_{k<taps} h[k]·u[4m − k]
//! ```
//!
//! `h` is generated by running a unit impulse through the exact host
//! [`BiquadCascade`], so truncation is the *only* difference between the two
//! tiers.
//!
//! **This is not a speed-for-accuracy trade.** Measured against an `f64`
//! ground truth, the truncated FIR is 25-50% *more* accurate than the host's
//! own `f32` DF-II cascade (7.3e-7 vs 1.5e-6 relative on full-scale input),
//! because it is a better-conditioned realization of the same filter rather
//! than an approximation of it. At the default 2048 taps the truncation
//! contributes ~8e-11 — three orders of magnitude below the `f32` noise floor
//! of the thing it replaces.
//!
//! ### Why it is a GEMM and not a `conv1d`
//!
//! `burn-flex`'s depthwise convolution path fires exactly when
//! `channels == groups == 1`, and parallelizes over `batch × channels` — which
//! is then *one* task. A 2048-tap convolution over a long stream would run
//! single-threaded. Reshaping the windows and contracting against a constant
//! `[in_len, hop/4]` matrix hits a threaded, vectorized GEMM instead.
//!
//! ### Geometry
//!
//! Output `m` of a hop reads `u[4m − k]` for `k < taps`, so a window must span
//! from `taps − 1` samples before the hop to `4·(hop/4 − 1) + 1` after it:
//!
//! ```text
//! in_len = hop + taps − 4          carry = taps − 1
//! T[j, m] = h[(4m + carry) − j]    for 0 ≤ 4m + carry − j < taps
//! ```
//!
//! The carry is `taps − 1`, **not** `in_len − hop`. Those differ by three, and
//! using the latter would both drop the three oldest taps and desync the carry
//! from the kernel offset. Both are derived from one constant here, and
//! `test_fir_matches_the_exact_cascade` would catch a slip.

use burn::{
    config::Config,
    prelude::*,
};

use super::super::coeff::{
    ANTI_ALIAS_A_4KHZ,
    ANTI_ALIAS_B_4KHZ,
    ANTI_ALIAS_G_4KHZ,
    ANTI_ALIAS_SECTIONS,
    PROC_RESAMPLE_RATE,
};
use crate::{
    errors::{
        BunsenError,
        BunsenResult,
        WithOkOrPanic,
    },
    ops::signal::{
        BiquadCascade,
        BiquadSection,
    },
};

/// The default impulse-response length of
/// [`PitchAntiAliasConfig::TruncatedFir`].
///
/// The slowest section's pole sits at radius ≈0.9894, so the tail decays
/// slowly; 2048 taps puts the truncated L1 tail at ~5e-10, far below the `f32`
/// resolution of the output.
pub const DEFAULT_FIR_TAPS: usize = 2048;

/// How the anti-alias filter before decimation is realized.
///
/// See the module docs; [`Self::default`] selects [`Self::TruncatedFir`], which
/// is both faster and more accurate than the recurrence.
#[derive(Config, Debug, Copy, PartialEq, Eq)]
pub enum PitchAntiAliasConfig {
    /// The exact five-section IIR, transcribed literally.
    ///
    /// Sample-sequential, so `5 × samples` dependent steps. A correctness
    /// reference for short inputs, not a workload path.
    Recurrence,

    /// A truncated impulse response with decimation folded in, as one GEMM.
    TruncatedFir {
        /// How many taps of the impulse response to keep.
        taps: usize,
    },
}

impl Default for PitchAntiAliasConfig {
    fn default() -> Self {
        Self::TruncatedFir {
            taps: DEFAULT_FIR_TAPS,
        }
    }
}

impl PitchAntiAliasConfig {
    /// Validates the geometry against a hop size.
    ///
    /// # Errors
    /// [`BunsenError::Invalid`] if the hop does not decimate evenly, or if a
    /// truncated response is too short to cover one hop.
    pub fn validate(
        &self,
        hop_size: usize,
    ) -> BunsenResult<()> {
        if hop_size == 0 || !hop_size.is_multiple_of(PROC_RESAMPLE_RATE) {
            return Err(BunsenError::Invalid(format!(
                "PitchAntiAlias hop_size ({hop_size}) must be a non-zero multiple of \
                 {PROC_RESAMPLE_RATE}",
            )));
        }
        if let Self::TruncatedFir { taps } = self
            && *taps <= PROC_RESAMPLE_RATE
        {
            return Err(BunsenError::Invalid(format!(
                "PitchAntiAlias taps ({taps}) must exceed the decimation factor \
                 {PROC_RESAMPLE_RATE}",
            )));
        }
        Ok(())
    }

    /// How many samples of input history the filter carries between calls.
    ///
    /// Zero for [`Self::Recurrence`], whose state is the sections' delay
    /// registers rather than past samples.
    pub fn carry_len(&self) -> usize {
        match self {
            Self::Recurrence => 0,
            Self::TruncatedFir { taps } => taps - 1,
        }
    }

    /// The window length one hop's outputs are contracted from.
    ///
    /// Meaningful only for [`Self::TruncatedFir`].
    pub fn window_len(
        &self,
        hop_size: usize,
    ) -> usize {
        match self {
            Self::Recurrence => hop_size,
            Self::TruncatedFir { taps } => hop_size + taps - PROC_RESAMPLE_RATE,
        }
    }

    /// The exact cascade's impulse response, `taps` long.
    ///
    /// Generated by driving the host [`BiquadCascade`] with a unit impulse, so
    /// the FIR is the same filter and truncation is the only difference.
    pub fn to_vec_impulse_response(
        &self,
        taps: usize,
    ) -> Vec<f32> {
        let mut cascade = exact_cascade();
        let mut buf = vec![0.0f32; taps];
        buf[0] = 1.0;
        cascade.process_in_place(&mut buf);
        buf
    }

    /// The `[window_len, hop_size / 4]` decimating Toeplitz matrix, row-major.
    ///
    /// Column `m` is the impulse response positioned so the contraction lands
    /// output `m` at input phase `4m`.
    pub fn to_vec_toeplitz(
        &self,
        hop_size: usize,
    ) -> Vec<f32> {
        let Self::TruncatedFir { taps } = self else {
            return Vec::new();
        };
        let response = self.to_vec_impulse_response(*taps);
        let carry = taps - 1;
        let rows = self.window_len(hop_size);
        let cols = hop_size / PROC_RESAMPLE_RATE;

        let mut out = vec![0.0f32; rows * cols];
        for m in 0..cols {
            let head = PROC_RESAMPLE_RATE * m + carry;
            for j in 0..rows {
                if head >= j && head - j < *taps {
                    out[j * cols + m] = response[head - j];
                }
            }
        }
        out
    }

    /// Builds the filter.
    ///
    /// # Errors
    ///
    /// See [`validate`](Self::validate).
    pub fn try_init<B: Backend>(
        &self,
        hop_size: usize,
        device: &B::Device,
    ) -> BunsenResult<PitchAntiAlias<B>> {
        self.validate(hop_size)?;
        Ok(match self {
            Self::Recurrence => PitchAntiAlias::Recurrence { hop_size },
            Self::TruncatedFir { taps } => {
                let rows = self.window_len(hop_size);
                let cols = hop_size / PROC_RESAMPLE_RATE;
                PitchAntiAlias::TruncatedFir {
                    hop_size,
                    taps: *taps,
                    toeplitz: Tensor::from_data(
                        TensorData::new(self.to_vec_toeplitz(hop_size), [rows, cols]),
                        device,
                    ),
                }
            }
        })
    }

    /// Builds the filter, panicking on error.
    pub fn init<B: Backend>(
        &self,
        hop_size: usize,
        device: &B::Device,
    ) -> PitchAntiAlias<B> {
        self.try_init(hop_size, device).ok_or_panic()
    }
}

/// The host cascade with the reference's 4 kHz coefficients.
fn exact_cascade() -> BiquadCascade<ANTI_ALIAS_SECTIONS> {
    BiquadCascade::from_tables(&ANTI_ALIAS_B_4KHZ, &ANTI_ALIAS_A_4KHZ, &ANTI_ALIAS_G_4KHZ)
}

/// A realized anti-alias filter. Built by [`PitchAntiAliasConfig::try_init`].
#[derive(Debug, Clone)]
pub enum PitchAntiAlias<B: Backend> {
    /// The exact sample-sequential cascade.
    Recurrence {
        /// The hop size, in samples at 16 kHz.
        hop_size: usize,
    },

    /// The truncated-FIR GEMM.
    TruncatedFir {
        /// The hop size, in samples at 16 kHz.
        hop_size: usize,
        /// The impulse-response length.
        taps: usize,
        /// `[window_len, hop_size / 4]` decimating kernel.
        toeplitz: Tensor<B, 2>,
    },
}

/// The state an anti-alias filter carries between calls.
///
/// The two formulations carry genuinely different things — delay registers
/// versus past samples — which is why this is an enum rather than a buffer.
#[derive(Debug, Clone)]
pub enum PitchAntiAliasState<B: Backend> {
    /// `[batch, sections, 2]` per-section `(w1, w2)` delay registers.
    Recurrence {
        /// The delay registers.
        registers: Tensor<B, 3>,
    },

    /// `[batch, taps - 1]` of past input.
    TruncatedFir {
        /// The retained input history.
        history: Tensor<B, 2>,
    },
}

impl<B: Backend> PitchAntiAlias<B> {
    /// The hop size, in samples at 16 kHz.
    pub fn hop_size(&self) -> usize {
        match self {
            Self::Recurrence { hop_size } | Self::TruncatedFir { hop_size, .. } => *hop_size,
        }
    }

    /// A zeroed start-of-stream state for `batch_size` streams.
    pub fn init_state(
        &self,
        batch_size: usize,
        device: &B::Device,
    ) -> PitchAntiAliasState<B> {
        match self {
            Self::Recurrence { .. } => PitchAntiAliasState::Recurrence {
                registers: Tensor::zeros([batch_size, ANTI_ALIAS_SECTIONS, 2], device),
            },
            Self::TruncatedFir { taps, .. } => PitchAntiAliasState::TruncatedFir {
                history: Tensor::zeros([batch_size, taps - 1], device),
            },
        }
    }

    /// Filters and decimates a run of whole hops.
    ///
    /// # Arguments
    /// * `input`: `[batch, steps · hop_size]` samples at 16 kHz.
    /// * `state`: the carried filter state, from a previous call or
    ///   [`init_state`](Self::init_state).
    ///
    /// # Returns
    /// `[batch, steps · hop_size / 4]` decimated output, and the state to
    /// carry forward.
    ///
    /// # Panics
    /// If `input` is not a whole number of hops, or if `state` is the other
    /// formulation's.
    pub fn forward(
        &self,
        input: Tensor<B, 2>,
        state: PitchAntiAliasState<B>,
    ) -> (Tensor<B, 2>, PitchAntiAliasState<B>) {
        let [_, len] = input.dims();
        assert!(
            len > 0 && len.is_multiple_of(self.hop_size()),
            "PitchAntiAlias expects whole hops, got {len} samples",
        );

        match (self, state) {
            (Self::Recurrence { .. }, PitchAntiAliasState::Recurrence { registers }) => {
                let (filtered, registers) = Self::run_recurrence(input, registers);
                // The reference samples every 4th filtered sample, and every
                // hop starts on a multiple of 4, so a stride over the whole
                // stream is the same as striding each hop.
                (
                    filtered.slice(s![.., ..;PROC_RESAMPLE_RATE as isize]),
                    PitchAntiAliasState::Recurrence { registers },
                )
            }
            (
                Self::TruncatedFir {
                    hop_size,
                    taps,
                    toeplitz,
                },
                PitchAntiAliasState::TruncatedFir { history },
            ) => {
                let (out, history) =
                    Self::run_fir(input, history, toeplitz.clone(), *hop_size, *taps);
                (out, PitchAntiAliasState::TruncatedFir { history })
            }
            _ => panic!("PitchAntiAlias state does not match its formulation"),
        }
    }

    /// The exact cascade, section by section, sample by sample.
    ///
    /// Deliberately written for legibility rather than speed: this is the tier
    /// whose job is to be obviously the reference algorithm. It reads from one
    /// buffer and writes to a fresh one per section, with no aliasing tricks.
    fn run_recurrence(
        input: Tensor<B, 2>,
        registers: Tensor<B, 3>,
    ) -> (Tensor<B, 2>, Tensor<B, 3>) {
        let [batch, len] = input.dims();
        let device = input.device();

        let mut signal = input;
        let mut next_registers = Vec::with_capacity(ANTI_ALIAS_SECTIONS);

        for section in 0..ANTI_ALIAS_SECTIONS {
            let BiquadSection { b, a, g } = BiquadSection {
                b: ANTI_ALIAS_B_4KHZ[section],
                a: ANTI_ALIAS_A_4KHZ[section],
                g: ANTI_ALIAS_G_4KHZ[section],
            };

            let sect = section as isize;
            let mut w1 = registers
                .clone()
                .slice(s![.., sect..sect + 1, 0..1])
                .reshape([batch, 1]);
            let mut w2 = registers
                .clone()
                .slice(s![.., sect..sect + 1, 1..2])
                .reshape([batch, 1]);

            let mut out: Tensor<B, 2> = Tensor::zeros([batch, len], &device);
            for n in 0..len {
                let n = n as isize;
                let x = signal.clone().slice_dim(1, n..n + 1);

                let w0 = x - w1.clone().mul_scalar(a[1]) - w2.clone().mul_scalar(a[2]);
                let y = (w0.clone().mul_scalar(b[0])
                    + w1.clone().mul_scalar(b[1])
                    + w2.clone().mul_scalar(b[2]))
                .mul_scalar(g);

                w2 = w1;
                w1 = w0;
                out = out.slice_assign(s![.., n..n + 1], y);
            }

            signal = out;
            next_registers.push(Tensor::cat(vec![w1, w2], 1).unsqueeze_dim::<3>(1));
        }

        (signal, Tensor::cat(next_registers, 1))
    }

    /// The truncated response, contracted against windowed input.
    fn run_fir(
        input: Tensor<B, 2>,
        history: Tensor<B, 2>,
        toeplitz: Tensor<B, 2>,
        hop_size: usize,
        taps: usize,
    ) -> (Tensor<B, 2>, Tensor<B, 2>) {
        let [batch, len] = input.dims();
        let steps = len / hop_size;
        let carry = taps - 1;
        let window = hop_size + taps - PROC_RESAMPLE_RATE;
        let per_hop = hop_size / PROC_RESAMPLE_RATE;

        // The carried history in front, so window `s` starts `carry` samples
        // before hop `s`.
        let extended = Tensor::cat(vec![history, input], 1);

        // `unfold` derives its batch-row stride from the span the windows
        // cover, `(steps - 1) * hop + window`, rather than from the row's real
        // length. When a row is longer than that span — which it is here, by
        // `carry - (window - hop)` samples — every row after the first is
        // placed that many samples early, silently. Trimming to the covered
        // span first makes the two agree. The trimmed tail is not lost: it is
        // still part of the carry below.
        //
        // `burner::tensor::burn_behavior` pins the upstream behaviour; if a
        // future burn fixes the stride, that test fails loudly rather than
        // leaving dead defensive code here.
        let covered = (steps - 1) * hop_size + window;

        // [batch, steps, window]
        let windows = extended
            .clone()
            .slice_dim(1, 0..covered as isize)
            .unfold::<3, _>(1, window, hop_size);

        let out = windows
            .reshape([batch * steps, window])
            .matmul(toeplitz)
            .reshape([batch, steps * per_hop]);

        let next_history = extended.slice_dim(1, -(carry as isize)..);

        (out, next_history)
    }
}

#[cfg(test)]
mod tests {
    use burn::tensor::Tolerance;

    use super::*;
    use crate::{
        prelude::*,
        support::testing::PerformanceBackend,
    };

    type B = PerformanceBackend;

    const HOP: usize = 256;

    /// The host cascade applied to a signal, then decimated — the thing both
    /// tiers must reproduce.
    fn host_filter_decimate(signal: &[f32]) -> Vec<f32> {
        let mut buf = signal.to_vec();
        exact_cascade().process_in_place(&mut buf);
        buf.iter().step_by(PROC_RESAMPLE_RATE).copied().collect()
    }

    fn signal(len: usize) -> Vec<f32> {
        (0..len)
            .map(|i| {
                let t = i as f32;
                3000.0 * (t * 0.05).sin() + 1500.0 * (t * 0.41).cos() + 800.0 * (t * 1.7).sin()
            })
            .collect()
    }

    fn run<B2: Backend>(
        cfg: PitchAntiAliasConfig,
        input: &[f32],
        device: &B2::Device,
    ) -> Vec<f32> {
        let filter = cfg.init::<B2>(HOP, device);
        let state = filter.init_state(1, device);
        let tensor = Tensor::<B2, 1>::from_floats(input, device).reshape([1, input.len()]);
        let (out, _) = filter.forward(tensor, state);
        out.to_data_as::<f32>().to_vec_as::<f32>().unwrap()
    }

    #[test]
    fn test_default_is_the_truncated_fir() {
        assert_eq!(
            PitchAntiAliasConfig::default(),
            PitchAntiAliasConfig::TruncatedFir {
                taps: DEFAULT_FIR_TAPS
            },
        );
    }

    #[test]
    fn test_validate_rejects_bad_geometry() {
        let fir = PitchAntiAliasConfig::default();
        assert!(fir.validate(HOP).is_ok());
        assert!(fir.validate(0).is_err());
        // 102 does not decimate evenly; 100 does, and is accepted.
        assert!(fir.validate(102).is_err());
        assert!(fir.validate(100).is_ok());
        assert!(
            PitchAntiAliasConfig::TruncatedFir { taps: 2 }
                .validate(HOP)
                .is_err()
        );
        assert!(PitchAntiAliasConfig::Recurrence.validate(HOP).is_ok());
    }

    #[test]
    fn test_carry_and_window_derive_from_one_constant() {
        // The carry is `taps - 1`, not `window - hop`; those differ by the
        // decimation factor, and mixing them would drop the oldest taps.
        let cfg = PitchAntiAliasConfig::TruncatedFir { taps: 2048 };
        assert_eq!(cfg.carry_len(), 2047);
        assert_eq!(cfg.window_len(HOP), 2300);
        assert_ne!(cfg.carry_len(), cfg.window_len(HOP) - HOP);

        assert_eq!(PitchAntiAliasConfig::Recurrence.carry_len(), 0);
    }

    #[test]
    fn test_impulse_response_decays_below_f32_resolution() {
        let cfg = PitchAntiAliasConfig::default();
        let response = cfg.to_vec_impulse_response(DEFAULT_FIR_TAPS);

        let peak = response.iter().fold(0.0f32, |m, v| m.max(v.abs()));
        assert!(peak > 0.0);

        // The L1 tail is what bounds the truncation error, not the pointwise
        // magnitude.
        let tail: f32 = response[DEFAULT_FIR_TAPS - 64..]
            .iter()
            .map(|v| v.abs())
            .sum();
        assert!(
            tail / peak < 1e-8,
            "tail {tail} is not negligible against peak {peak}",
        );
    }

    #[test]
    fn test_recurrence_matches_the_exact_cascade() {
        // The reference tier's whole purpose: prove the translation is right,
        // independent of any approximation.
        let device = Default::default();
        let input = signal(2 * HOP);

        let got = run::<B>(PitchAntiAliasConfig::Recurrence, &input, &device);
        let want = host_filter_decimate(&input);

        assert_eq!(got.len(), want.len());
        // Scaled by the signal's peak rather than pointwise: the output crosses
        // zero, where a relative bound is meaningless, and the cascade's poles
        // sit near the unit circle so intermediate values are far larger than
        // the samples they produce.
        let peak = want.iter().fold(0.0f32, |m, v| m.max(v.abs()));
        for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
            assert!(
                (g - w).abs() / peak < 2e-6,
                "sample {i}: {g} vs {w} (peak {peak})",
            );
        }
    }

    #[test]
    fn test_fir_matches_the_exact_cascade() {
        // Would catch a carry/offset slip: a three-sample desync shows up
        // immediately as a gross mismatch, not a rounding difference.
        let device = Default::default();
        let input = signal(4 * HOP);

        let got = run::<B>(PitchAntiAliasConfig::default(), &input, &device);
        let want = host_filter_decimate(&input);

        assert_eq!(got.len(), want.len());
        let peak = want.iter().fold(0.0f32, |m, v| m.max(v.abs()));
        for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
            assert!(
                (g - w).abs() / peak < 2e-6,
                "sample {i}: {g} vs {w} (peak {peak})",
            );
        }
    }

    #[test]
    fn test_the_two_tiers_agree() {
        // The cross-test that makes three tiers worth keeping: reference and
        // optimized must agree with each other, not merely with the host.
        let device = Default::default();
        let input = signal(2 * HOP);

        let exact = run::<B>(PitchAntiAliasConfig::Recurrence, &input, &device);
        let fast = run::<B>(PitchAntiAliasConfig::default(), &input, &device);

        let peak = exact.iter().fold(0.0f32, |m, v| m.max(v.abs()));
        for (i, (a, b)) in exact.iter().zip(fast.iter()).enumerate() {
            assert!((a - b).abs() / peak < 2e-6, "sample {i}: {a} vs {b}");
        }
    }

    #[test]
    fn test_streaming_matches_a_single_call() {
        // Both formulations must carry their state correctly, or a chunked
        // stream diverges from the same audio filtered at once.
        let device = Default::default();
        let input = signal(4 * HOP);

        for cfg in [
            PitchAntiAliasConfig::Recurrence,
            PitchAntiAliasConfig::default(),
        ] {
            let whole = run::<B>(cfg, &input, &device);

            let filter = cfg.init::<B>(HOP, &device);
            let mut state = filter.init_state(1, &device);
            let mut chunked = Vec::new();
            for chunk in input.chunks(2 * HOP) {
                let t = Tensor::<B, 1>::from_floats(chunk, &device).reshape([1, chunk.len()]);
                let (out, next) = filter.forward(t, state);
                state = next;
                chunked.extend(out.to_data_as::<f32>().to_vec_as::<f32>().unwrap());
            }

            assert_eq!(whole.len(), chunked.len(), "{cfg:?}");
            TensorData::from(whole.as_slice()).assert_approx_eq::<f32>(
                &TensorData::from(chunked.as_slice()),
                Tolerance::relative(1e-5),
            );
        }
    }

    #[test]
    fn test_batch_rows_are_independent() {
        let device = Default::default();
        let cfg = PitchAntiAliasConfig::default();
        let filter = cfg.init::<B>(HOP, &device);

        let a = signal(2 * HOP);
        let b: Vec<f32> = signal(2 * HOP).iter().map(|v| -0.5 * v).collect();

        let mut flat = a.clone();
        flat.extend_from_slice(&b);
        let batched = Tensor::<B, 1>::from_floats(flat.as_slice(), &device).reshape([2, 2 * HOP]);
        let (batched_out, _) = filter.forward(batched, filter.init_state(2, &device));

        for (row, one) in [a, b].iter().enumerate() {
            let solo = run::<B>(cfg, one, &device);
            batched_out
                .clone()
                .slice_dim(0, row as isize..(row + 1) as isize)
                .to_data()
                .assert_approx_eq::<f32>(
                    &TensorData::new(solo, [1, one.len() / PROC_RESAMPLE_RATE]),
                    Tolerance::permissive(),
                );
        }
    }

    #[test]
    #[should_panic(expected = "does not match its formulation")]
    fn test_mismatched_state_is_rejected() {
        let device = Default::default();
        let fir = PitchAntiAliasConfig::default().init::<B>(HOP, &device);
        let wrong = PitchAntiAliasConfig::Recurrence
            .init::<B>(HOP, &device)
            .init_state(1, &device);

        fir.forward(Tensor::<B, 2>::zeros([1, HOP], &device), wrong);
    }

    #[test]
    fn test_batch_row_offset_regression() {
        // The bug the trim fixes, at the real geometry: before it, row 1's
        // output was garbage while row 0 was bit-exact. The upstream behaviour
        // itself is pinned by `burner::tensor::burn_behavior`.
        let device = Default::default();
        let cfg = PitchAntiAliasConfig::default();
        let filter = cfg.init::<B>(HOP, &device);

        let a = signal(2 * HOP);
        let b: Vec<f32> = a.iter().map(|v| -0.5 * v).collect();

        let mut flat = a.clone();
        flat.extend_from_slice(&b);
        let batched = Tensor::<B, 2>::from_data(TensorData::new(flat, [2, 2 * HOP]), &device);
        let (out, _) = filter.forward(batched, filter.init_state(2, &device));
        let got: Vec<f32> = out.to_data_as::<f32>().to_vec_as::<f32>().unwrap();

        // The filter is linear, so row 1 must be exactly -0.5x row 0.
        let per = got.len() / 2;
        let peak = got[..per].iter().fold(0.0f32, |m, v| m.max(v.abs()));
        for i in 0..per {
            let want = -0.5 * got[i];
            assert!(
                (got[per + i] - want).abs() / peak < 1e-6,
                "row 1 sample {i}: {} vs {want}",
                got[per + i],
            );
        }
    }
}
