[package]
name = "lbm2d_vis"
publish = false
edition.workspace = true
rust-version.workspace = true

[dependencies]
clockmill = { path = "../.." }

burn = { workspace = true, features = ["fusion", "autotune"] }

clap = { workspace = true, features = ["derive"] }
indicatif = { workspace = true }

piston = { workspace = true }
piston2d-graphics = { workspace = true }
pistoncore-glutin_window = { workspace = true }
piston2d-opengl_graphics = { workspace = true }
gl = { workspace = true }
rand = { workspace = true }

[lints]
workspace = true

[features]
default = []
cuda = ["burn/cuda"]
metal = ["burn/metal"]
wgpu = ["burn/wgpu"]
flex = ["burn/flex"]
