#!/usr/bin/env python3
"""Generate a shard set's SHA-256 table from a Hugging Face repository listing.

Run once; commit the output. Regenerating is not part of CI.

    python3 tools/gen_shard_digests.py

The listing is read at a pinned revision through the hub's tree API, which
pages 100 entries at a time and reports each LFS file's `oid`: its SHA-256.
The output is a Rust source file holding one `&[&str]` table, index-ordered,
that a `StaticShardSetDescriptor` points at with `StaticShardDigests::Table`.
The descriptor's `base_urls` should resolve the same revision, so the digests
and the files can never drift apart.

Standard library only: no venv needed.
"""

import argparse
import json
import pathlib
import re
import sys
import textwrap
import urllib.request

HERE = pathlib.Path(__file__).resolve().parent.parent

SETS = {
    # name: (repo, revision, file-name regex with one `index` group, rust output, rust static)
    "fineweb-edu-100b-shuffle": (
        "karpathy/fineweb-edu-100b-shuffle",
        "4c8f30d6756da75362432a4d5569e1b229263b71",
        r"shard_(?P<index>\d{5})\.parquet",
        "crates/public/bunsen/src/kits/gpts/nanochat/datasets/fineweb_edu_100b_shuffle_digests.rs",
        "FINEWEB_EDU_100B_SHUFFLE_SHA256",
    ),
}


def listing(repo, revision):
    """Every entry of the repository tree at `revision`, following the pages."""
    url = f"https://huggingface.co/api/datasets/{repo}/tree/{revision}?recursive=true&expand=true&limit=100"
    entries = []
    while url:
        with urllib.request.urlopen(url) as response:
            entries.extend(json.load(response))
            link = response.headers.get("Link", "")
            match = re.search(r'<([^>]+)>;\s*rel="next"', link)
            url = match.group(1) if match else None
    return entries


def digests(entries, pattern):
    """`index -> sha256` for the entries whose path matches `pattern`."""
    table = {}
    for entry in entries:
        match = re.fullmatch(pattern, entry["path"])
        if not match:
            continue
        lfs = entry.get("lfs")
        if not lfs:
            sys.exit(f"{entry['path']}: not an LFS file; it has no sha256")
        table[int(match.group("index"))] = lfs["oid"]
    if not table:
        sys.exit(f"no path matched {pattern!r}")
    expected = list(range(len(table)))
    if sorted(table) != expected:
        sys.exit(f"shard indices are not contiguous from 0: {sorted(table)[:5]}…{sorted(table)[-5:]}")
    return [table[i] for i in expected]


def doc(prefix, text, width=80):
    """`text` as comment lines under `prefix`, wrapped as rustfmt would."""
    body = width - len(prefix) - 1
    return [f"{prefix} {line}" for line in textwrap.wrap(text, body, break_long_words=False, break_on_hyphens=False)]


def render(name, repo, revision, pattern, static, sha256s):
    lines = doc("//!", f"SHA-256 of every shard of `{name}`, index-ordered.")
    lines.append("//!")
    lines += doc(
        "//!",
        f"Generated by `tools/gen_shard_digests.py` from the Hugging Face tree listing of `{repo}` "
        f"at revision `{revision}` ({len(sha256s)} files matching `{pattern}`). Do not edit; regenerate.",
    )
    lines.append("")
    lines += doc("///", f"SHA-256 of shard `i` of `{name}`, as the hub's LFS pointers record it.")
    lines.append(f"pub static {static}: &[&str] = &[")
    lines.extend(f'    "{sha}",' for sha in sha256s)
    lines.append("];")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("sets", nargs="*", default=list(SETS), help="sets to generate (default: all)")
    args = parser.parse_args()
    for name in args.sets:
        repo, revision, pattern, out, static = SETS[name]
        sha256s = digests(listing(repo, revision), pattern)
        path = HERE / out
        path.write_text(render(name, repo, revision, pattern, static, sha256s))
        print(f"{name}: {len(sha256s)} digests -> {path.relative_to(HERE)}")


if __name__ == "__main__":
    main()
