[package]
name = "bunsen-onnx-gen"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
description = "Bunsen utility burn (onnx => rust + burnpack) model generation."

[dependencies]
burn = { workspace = true, features = ["store"] }
burn-store = { workspace = true }
document-features = { workspace = true }

[build-dependencies]
burn-onnx = { workspace = true }

[lints]
workspace = true

[features]
default = ["silero"]
silero = []