[package]
name = "conway"
publish = false
edition.workspace = true
rust-version.workspace = true


[lints]
workspace = true


[features]
## Make `--device cuda` available.
cuda = ["bunsen-app/cuda"]
## Make `--device metal` available.
metal = ["bunsen-app/metal"]
## Make `--device vulkan` available.
vulkan = ["bunsen-app/vulkan"]
## Make `--device wgpu` available.
wgpu = ["bunsen-app/wgpu"]

[dependencies]
burn = { workspace = true, features = ["fusion", "autotune"] }
bunsen = { path = "../../crates/public/bunsen" }

log = { workspace = true }
bunsen-app = { path = "../../crates/dev/bunsen-app" }
clap = { workspace = true, features = ["derive"] }

indicatif = { workspace = true }

piston = { workspace = true }
piston2d-graphics = { workspace = true }
pistoncore-glutin_window = { workspace = true }
piston2d-opengl_graphics = { workspace = true }
gl = { workspace = true }

