[package]
name = "train-chat"
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
zsl-data-cache = { path = "../zsl-data-cache" }
bunsen = { path = "../../crates/bunsen" }
bunsen-preview-chat-dataloader = { path = "../../crates/bunsen-preview-chat-dataloader" }

num-traits = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
log = { workspace = true }
wordchipper = { workspace = true, features = ["client"] }
wordchipper-cli-util = { workspace = true }
burn = { workspace = true, features = ["train", "fusion", "autotune"] }

[features]
default = ["wgpu"]
cuda = ["burn/cuda"]
wgpu = ["burn/wgpu"]
metal = ["burn/metal"]

[lints]
workspace = true
