name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly --profile minimal --component rustfmt
      - run: cargo +nightly fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --component clippy
      - run: cargo clippy --no-deps -- -D warnings

  test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Cache Cargo binaries and dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      # - name: Install Tools
      #   run: cargo install -q cargo-tarpaulin || true

      # - name: Build and Test
      #   run: |
      #     cargo tarpaulin --features=wgpu --coveralls=${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Docs
        run: cargo doc --no-deps --all-features

      - name: Build and Test
        run: cargo test --features=flex

      - name: No default features build.
        run: cargo test -p bunsen --no-default-features
